apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service-deployment
  labels:
    app: orders

spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: realityadmin/orders:1.1.0
        ports:
          - containerPort: 8083
