FROM golang:1.26

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY orders ./orders
COPY products ./products
COPY users ./users
RUN go build -o main ./orders/cmd/*.go
EXPOSE 8083

CMD ["./main"]
