apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service-deployment
  labels:
    app: users

spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: realityadmin/users:1.0.0
        ports:
          - containerPort: 8081
